# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
import os
from snakemake.utils import min_version

min_version("7.18.2")

configfile: "config/config.yaml"

# list all subfolders in input_dir
sample_dirs = os.listdir(config['input_dir'])

include: "rules/concatenate_fastq.smk"
include: "rules/pychopper_first_round.smk"
include: "rules/pychopper_second_round.smk"
include: "rules/merge_cDNA_reads.smk"
include: "rules/polyA_removal.smk"
include: "rules/SSP_removal.smk"
include: "rules/mapping_genome.smk"
include: "rules/transcript_file.smk"

rule all:
  input:
    expand(os.path.join(config['output_mapping'], "genome", "{sample}_genome.fastq"), sample=sample_dirs)
